# Generated by Django 4.1.7 on 2023-09-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
            options={"db_table": "AD",},
        ),
        migrations.CreateModel(
            name="answer_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.CharField(max_length=255)),
            ],
            options={"db_table": "answer_1",},
        ),
        migrations.CreateModel(
            name="answer_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.ImageField(max_length=255, upload_to="")),
                ("answer", models.ImageField(max_length=255, upload_to="")),
            ],
            options={"db_table": "answer_2",},
        ),
        migrations.CreateModel(
            name="answer_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.CharField(max_length=255)),
            ],
            options={"db_table": "answer_3",},
        ),
        migrations.CreateModel(
            name="login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("ip", models.CharField(max_length=255)),
                ("browser", models.CharField(max_length=255)),
                ("time", models.DateTimeField(max_length=255)),
            ],
            options={"db_table": "login",},
        ),
        migrations.CreateModel(
            name="phrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("ph", models.CharField(max_length=255)),
                ("time", models.DateTimeField(max_length=255)),
            ],
            options={"db_table": "phrase",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("state", models.BooleanField(default=True)),
            ],
            options={"db_table": "user",},
        ),
    ]
