# Generated by Django 4.1.7 on 2023-09-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AD",
            fields=[
                (
                    "username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="answer_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, unique=True)),
                ("answer", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="answer_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.ImageField(max_length=255, unique=True, upload_to=""),
                ),
                (
                    "answer",
                    models.ImageField(max_length=255, unique=True, upload_to=""),
                ),
            ],
        ),
        migrations.CreateModel(
            name="answer_3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, unique=True)),
                ("answer", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="login",
            fields=[
                (
                    "username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("ip", models.CharField(max_length=255, unique=True)),
                ("browser", models.CharField(max_length=255, unique=True)),
                ("time", models.TimeField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="phrase",
            fields=[
                (
                    "username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("ph", models.CharField(max_length=255, unique=True)),
                ("time", models.TimeField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("phone_number", models.CharField(max_length=255, unique=True)),
                (
                    "username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={"db_table": "user",},
        ),
    ]
